name: Hourly Feature Engineering

on:
  schedule:
    # Run at minute 0 every hour (UTC)
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  feature_engineering:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run feature engineering script
        env:
          # Optional secrets to allow Hopsworks authentication from the script
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
          OPENWEATHER_API_KEY : ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_URL: ${{ secrets.HOPSWORKS_URL }}
        run: |
          echo "Running feature_engineering.py"
          python feature_engineering.py
